### ISSUE TITLE
Bug: Editing List Title - error

### ISSUE THREAD

**Issue by DaraOloughlin** [pixaura/cliqrex-main#200] opened 2022-08-09 18:49 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/pixaura/cliqrex-main/issues) for a bug report similar to mine, in vain

### What platform are you using?

iOS App

### Operating System Version

iPhone 11, ios 15.5

### Last Known Working CliqRex version

n/a

### Expected Behavior

When editing the settings for a list (within My Stuff > any Custom List > gear icon), I expected to be able to change the name of the list, see the new name replace the old name, and press save to close the editing window.

### Actual Behavior

In list settings (My Stuff > any Custom List > gear icon), I clicked in the title field to edit the name, and the old name moved up above the text field rather than either disappearing or remaining highlighted. The old name remained floating above the new name as I typed it. When I pressed Save, the window did not close (but it did save the new name). I was only able to close the window by using the drop-down carrot at the top of the settings window.

### Steps to reproduce

1. go to My Stuff > any custom list > gear icon
2. click in the text field to edit the name
3. see old name hover above text
4. press save
5. see that window doesn't close
6. close window with carrot drop down at top of settings window

### Screenshots

You can see My Stuff reload each time I press Save, but the window doesn't close. You can also see the old title floating above new one.

https://user-images.githubusercontent.com/101932440/183737827-44cc8c13-745a-4106-b394-e21c8aef7cf7.MP4

.

**Comment by palepinkdot** [comment] 2022-08-09 19:05
Duplicate of #195

**Closed by palepinkdot** 2022-08-09 19:05 UTC
Labels: wontfix, duplicate
