### ISSUE TITLE
User Profile - Cliq Member

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#175] opened 2022-07-07 14:43 UTC
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.

### Description

As a CliqRex user, I want to be able to view another user's profile, including details and lists. If they're in my Cliq I can REMOVE them from my Cliq.

### Acceptance Criteria

-User Profile should display user image with affinity ring, name, username, affinity match % (written out), about/info, and social links if added.
-User Profile can be shared.
-Lists will include Top Lists (Top TV Shows, Top Movies, Top Podcasts), In Progress, Custom Lists, and Followed Lists for the user you're viewing.
-All lists will be formatted the same.
-Media items in the list are left-right scrollable
-Media items are sorted by HIGHEST RATING first in Top Lists
-Media items are sorted by NEWEST item first in Custom Lists
-Media items display the user that you're viewing ratings. Since this user is IN MY Cliq, ratings are in PURPLE
-Media items are clickable to the detail card
-Custom Lists and Followed Lists can be shared (the video says Favorited but going with Followed).

### Exceptions

- - Custom and Followed Lists can be followed. An empty star shows it’s not being followed. A filled in (yellow) star shows it’s being followed.

### Screenshots

![image-6](https://user-images.githubusercontent.com/15748883/177801667-7c667774-1b25-419a-8a50-a7644cf87eef.jpeg)
![user_profile_cliq_member](https://user-images.githubusercontent.com/15748883/177801677-7cc83a7a-5c29-41b1-9ecd-702afe6e75e3.png)

https://user-images.githubusercontent.com/15748883/179511147-c051997f-6a92-44e1-a5cc-9fe765c6afc6.mp4

**Comment by palepinkdot** [comment] 2022-08-01 19:16
this is a duplicate of #174, the screenshots aren't even different.

**Closed by palepinkdot** 2022-08-01 19:16 UTC
Labels: change, P2, :clock1: medium, duplicate
